# Feature Engineering Experiments

**Purpose**: Create target label, do some experiments

**Input**: data/processed/ochota_stops_with_amenities.csv

In [2]:
from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
PROJECT_DIR = Path.cwd().parent.parent
PROCESSED_CSV = PROJECT_DIR / "data" / "processed" / "ochota_stops_with_amenities.csv"

In [4]:
df = pd.read_csv(PROCESSED_CSV)
df.head()

,stop_id,stop_name,stop_lat,stop_lon,shop_related_count,hospital_related_count,school_related_count
0,328601,Rakowiecka - Sanktuarium,52.205211,20.999071,10,18,13
1,328602,Rakowiecka - Sanktuarium,52.206381,20.999281,10,17,13
2,328603,Rakowiecka - Sanktuarium,52.205155,20.999400,11,18,14
3,328604,Rakowiecka - Sanktuarium,52.205617,20.999336,11,17,14
4,400102,Pl. Zawiszy,52.224696,20.987462,14,19,12

In [ ]:
from src.config import AMENITY_TAGS
for tag in AMENITY_TAGS:
    print(tag)

shop_related
hospital_related
school_related

In [ ]:
df['target'] = 0

essential_cols = [f"{tag}_count" for tag in AMENITY_TAGS]
df["target"] = 1
for count_col in essential_cols:
    df.loc[df[count_col] < 5, "target"] = 0

In [27]:
print(f"There are {len(df[df['target'] == 0])} labels '0' and {len(df[df['target'] == 1])} labels '1'.")

There are 66 labels '0' and 153 labels '1'.

In [30]:
df

,stop_id,stop_name,stop_lat,stop_lon,shop_related_count,hospital_related_count,school_related_count,target
0,328601,Rakowiecka - Sanktuarium,52.205211,20.999071,10,18,13,1
1,328602,Rakowiecka - Sanktuarium,52.206381,20.999281,10,17,13,1
2,328603,Rakowiecka - Sanktuarium,52.205155,20.999400,11,18,14,1
3,328604,Rakowiecka - Sanktuarium,52.205617,20.999336,11,17,14,1
4,400102,Pl. Zawiszy,52.224696,20.987462,14,19,12,1
...,...,...,...,...,...,...,...,...
214,520302,Gizów,52.224675,20.944829,7,11,13,1
215,520401,Goleszowska,52.223680,20.941862,11,12,16,1
216,520402,Goleszowska,52.223444,20.940879,9,12,16,1
217,5902,Warszawa Zachodnia (Peron 9),52.222057,20.961357,6,1,1,0
218,5903,Warszawa Wola,52.229784,20.957835,6,10,11,1